# Chapter 4

This chapter covers the usage of `numpy` module for efficient array operations.

## Learning Goals

- `numpy` arrays
- `numpy` basics
- Vectorized computation, and broadcasting
- Array axes

## Authors

- Mert Candar, mccandar@gmail.com
- Aras Kahraman, aras.kahraman@hotmail.com

## Learning Curve Boosters

https://github.com/kyclark/tiny_python_projects

https://github.com/Python-World/python-mini-projects/tree/master/projects

https://github.com/rlvaugh/Impractical_Python_Projects

## An Introduction to `numpy`



The module `numpy` is a handy and comprehensive scientific computation library.

* It is fast.
* Memory efficient.
* Easier to code.

We will utilize the power of numpy via, arrays, i.e. vectors, matrices and n-dimensional arrays.


## Section 1: Arrays

A systematic storage of similar type items together in memory.

In [390]:
import numpy as np

In [393]:
d = [4,5,6,7]
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [394]:
type(arr)

numpy.ndarray

In [ ]:
# np.ndarray <--- class
# m = np.array()
# m <--- instance (object) of np.ndarray class

In [395]:
d = (4,5,6,7)
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [396]:
d = range(5)
arr = np.array(d)
arr

array([0, 1, 2, 3, 4])

In [398]:
arr.shape

(5,)

In [400]:
arr.ndim

1

In [407]:
d = [
    [1,6.84,3,6],
    [-1,4,-3,17],
    [38,1,-0.45,0.0],
]
arr = np.array(d)
arr

array([[ 1.  ,  6.84,  3.  ,  6.  ],
       [-1.  ,  4.  , -3.  , 17.  ],
       [38.  ,  1.  , -0.45,  0.  ]])

In [408]:
arr.shape

(3, 4)

In [409]:
arr.ndim

2

#### Indexing

In [416]:
d = [5,2,7,8,12,5,1,2,6,3,7,-3,12,41,2,4,1]
arr = np.array(d)
arr

array([ 5,  2,  7,  8, 12,  5,  1,  2,  6,  3,  7, -3, 12, 41,  2,  4,  1])

In [417]:
arr.ndim

1

In [418]:
arr.shape

(17,)

In [419]:
arr[0]

5

In [420]:
arr[3:12]

array([ 8, 12,  5,  1,  2,  6,  3,  7, -3])

In [421]:
arr[3:12:4]

array([ 8,  2, -3])

In [424]:
arr[12:3:-1]

array([12, -3,  7,  3,  6,  2,  1,  5, 12])

In [425]:
arr[12:3:-4]

array([12,  6, 12])

In [426]:
d = [
    [5,7,3],
    [8,3,6],
    [4,8,4],
    [9,7,0],
    [1,4,0],
    [6,3,1]
]
arr = np.array(d)
arr

array([[5, 7, 3],
       [8, 3, 6],
       [4, 8, 4],
       [9, 7, 0],
       [1, 4, 0],
       [6, 3, 1]])

In [427]:
arr.ndim

2

In [428]:
arr.shape

(6, 3)

In [429]:
arr[0]

array([5, 7, 3])

In [431]:
arr[3:]

array([[9, 7, 0],
       [1, 4, 0],
       [6, 3, 1]])

In [433]:
arr[2,2]

4

In [434]:
arr[2][2]

4

In [436]:
arr[:3,1]

array([7, 3, 8])

In [437]:
arr[5,:2]

array([6, 3])

Index | 0 | 1 | 2 |
--- | --- | --- | --- |
**0** | 5 | 7 | 3 |
**1** | 8 | 3 | 6 |
**2** | 4 | 8 | 4 |
**3** | 9 | 7 | 0 |
**4** | 1 | 4 | 0 |
**5** | 6 | 3 | 1 |

In [438]:
arr[1:,2]

array([6, 4, 0, 0, 1])

In [439]:
arr[1:4,1:2]

array([[3],
       [8],
       [7]])

In [440]:
arr[-3:,1:]

array([[7, 0],
       [4, 0],
       [3, 1]])

In [441]:
arr

array([[5, 7, 3],
       [8, 3, 6],
       [4, 8, 4],
       [9, 7, 0],
       [1, 4, 0],
       [6, 3, 1]])

In [442]:
d = [
    [
        [5,7,3],
        [8,3,6]
    ],
    [
        [4,8,4],
        [9,7,0]
    ],
    [
        [1,4,0],
        [6,3,1]
    ]
]
arr = np.array(d)
arr

array([[[5, 7, 3],
        [8, 3, 6]],

       [[4, 8, 4],
        [9, 7, 0]],

       [[1, 4, 0],
        [6, 3, 1]]])

In [443]:
arr.ndim

3

In [444]:
arr.shape

(3, 2, 3)

In [445]:
arr[0]

array([[5, 7, 3],
       [8, 3, 6]])

In [446]:
arr[0].ndim

2

In [447]:
arr[0].shape

(2, 3)

In [448]:
arr[1:]

array([[[4, 8, 4],
        [9, 7, 0]],

       [[1, 4, 0],
        [6, 3, 1]]])

In [449]:
arr[1,0]

array([4, 8, 4])

In [451]:
arr[1,0,2]

4

In [452]:
arr[1,:,2]

array([4, 0])

In [453]:
arr[:,:,2]

array([[3, 6],
       [4, 0],
       [0, 1]])

In [454]:
arr[:,1,:]

array([[8, 3, 6],
       [9, 7, 0],
       [6, 3, 1]])

In [455]:
arr

array([[[5, 7, 3],
        [8, 3, 6]],

       [[4, 8, 4],
        [9, 7, 0]],

       [[1, 4, 0],
        [6, 3, 1]]])

In [457]:
arr.reshape((9,2))

array([[5, 7],
       [3, 8],
       [3, 6],
       [4, 8],
       [4, 9],
       [7, 0],
       [1, 4],
       [0, 6],
       [3, 1]])

In [459]:
arr.reshape((3,3,2))

array([[[5, 7],
        [3, 8],
        [3, 6]],

       [[4, 8],
        [4, 9],
        [7, 0]],

       [[1, 4],
        [0, 6],
        [3, 1]]])

In [461]:
arr.reshape((1,-1))

array([[5, 7, 3, 8, 3, 6, 4, 8, 4, 9, 7, 0, 1, 4, 0, 6, 3, 1]])

In [463]:
arr.reshape((-1,1))

array([[5],
       [7],
       [3],
       [8],
       [3],
       [6],
       [4],
       [8],
       [4],
       [9],
       [7],
       [0],
       [1],
       [4],
       [0],
       [6],
       [3],
       [1]])

In [464]:
arr.reshape((9,-1))

array([[5, 7],
       [3, 8],
       [3, 6],
       [4, 8],
       [4, 9],
       [7, 0],
       [1, 4],
       [0, 6],
       [3, 1]])

In [465]:
arr.reshape((1,1,-1))

array([[[5, 7, 3, 8, 3, 6, 4, 8, 4, 9, 7, 0, 1, 4, 0, 6, 3, 1]]])

In [466]:
arr.reshape((-1,1,1))

array([[[5]],

       [[7]],

       [[3]],

       [[8]],

       [[3]],

       [[6]],

       [[4]],

       [[8]],

       [[4]],

       [[9]],

       [[7]],

       [[0]],

       [[1]],

       [[4]],

       [[0]],

       [[6]],

       [[3]],

       [[1]]])

In [467]:
arr.reshape((-1,2,3,1))

array([[[[5],
         [7],
         [3]],

        [[8],
         [3],
         [6]]],


       [[[4],
         [8],
         [4]],

        [[9],
         [7],
         [0]]],


       [[[1],
         [4],
         [0]],

        [[6],
         [3],
         [1]]]])

### 1.1 Broadcasting

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [486]:
a = np.array([3,5,-1])

In [487]:
a + 1

array([4, 6, 0])

In [488]:
a - 5

array([-2,  0, -6])

In [489]:
a * 2

array([ 6, 10, -2])

In [492]:
a / 3

array([ 1.        ,  1.66666667, -0.33333333])

In [493]:
a ** 2

array([ 9, 25,  1])

In [494]:
a % 2

array([1, 1, 1])

In [495]:
a // 3

array([ 1,  1, -1])

In [497]:
b = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

In [499]:
b + 3

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [500]:
b - 2

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [501]:
b * 10

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [502]:
b / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.33333333, 0.66666667, 1.        ],
       [0.33333333, 0.66666667, 1.        ]])

In [503]:
b % 3

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [504]:
b // 3

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [505]:
b ** 3

array([[ 1,  8, 27],
       [ 1,  8, 27],
       [ 1,  8, 27]])

In [506]:
a = np.array([3,5,-1])
b = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

In [507]:
print("Dimension of a:",a.ndim)
print("Dimension of b:",b.ndim)

Dimension of a: 1
Dimension of b: 2


In [508]:
print("Shape of a:",a.shape)
print("Shape of b:",b.shape)

Shape of a: (3,)
Shape of b: (3, 3)


In [509]:
a + a

array([ 6, 10, -2])

In [510]:
a + b

array([[4, 7, 2],
       [4, 7, 2],
       [4, 7, 2]])

In [511]:
a.reshape((-1,1))

array([[ 3],
       [ 5],
       [-1]])

In [513]:
a.reshape((-1,1)) + b

array([[4, 5, 6],
       [6, 7, 8],
       [0, 1, 2]])

In [515]:
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [516]:
b.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [517]:
a + b.T

array([[4, 6, 0],
       [5, 7, 1],
       [6, 8, 2]])

In [518]:
a.reshape((-1,1)) + b.T

array([[4, 4, 4],
       [7, 7, 7],
       [2, 2, 2]])

In [519]:
a * b

array([[ 3, 10, -3],
       [ 3, 10, -3],
       [ 3, 10, -3]])

In [520]:
a * b.T

array([[ 3,  5, -1],
       [ 6, 10, -2],
       [ 9, 15, -3]])

In [521]:
a.reshape((-1,1)) * b

array([[ 3,  6,  9],
       [ 5, 10, 15],
       [-1, -2, -3]])

In [522]:
a.reshape((-1,1)) * b.T

array([[ 3,  3,  3],
       [10, 10, 10],
       [-3, -3, -3]])

In [523]:
b = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

In [524]:
b + b

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [525]:
b + b.T

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [526]:
b * b

array([[1, 4, 9],
       [1, 4, 9],
       [1, 4, 9]])

In [527]:
b / b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [528]:
b * b.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### 1.2 Basic Features

In [531]:
arr = np.array([ 2, -3,  2, 4, 6, 8, 8, -25, 0.1, 8, 12, 5])

In [532]:
arr.shape

(12,)

In [533]:
arr.max()

12.0

In [534]:
arr.min()

-25.0

In [535]:
arr.mean()

2.2583333333333333

In [536]:
arr.std()

9.100408263125097

In [537]:
arr.var()

82.81743055555555

In [538]:
arr.sum()

27.1

In [539]:
arr.cumsum()

array([ 2. , -1. ,  1. ,  5. , 11. , 19. , 27. ,  2. ,  2.1, 10.1, 22.1,
       27.1])

In [540]:
arr.prod()

22118400.0

In [541]:
arr.cumprod()

array([ 2.00000e+00, -6.00000e+00, -1.20000e+01, -4.80000e+01,
       -2.88000e+02, -2.30400e+03, -1.84320e+04,  4.60800e+05,
        4.60800e+04,  3.68640e+05,  4.42368e+06,  2.21184e+07])

In [543]:
arr.ptp()

37.0

In [544]:
arr.argmin()

7

In [545]:
arr.argmax()

10

In [548]:
idx = arr.argsort()
idx

array([ 7,  1,  8,  0,  2,  3, 11,  4,  5,  6,  9, 10])

In [549]:
arr[idx]

array([-25. ,  -3. ,   0.1,   2. ,   2. ,   4. ,   5. ,   6. ,   8. ,
         8. ,   8. ,  12. ])

### 1.3 Increasing Dimensions

In [550]:
d = [
    [1, 5, 7],
    [4, 5, 3],
    [1, 5, 6],
    [1, 4, 6],
    [5, 2, 4],
    [6, 2, 5],
    [4, 4, 4],
    [4, 4, 7]
]
arr = np.array(d)

In [553]:
arr.max()

7

In [554]:
arr.min()

1

In [555]:
arr.mean()

4.125

In [556]:
arr.std()

1.7154324041865752

In [557]:
arr.var()

2.9427083333333335

In [558]:
arr.sum()

99

In [559]:
arr.cumsum()

array([ 1,  6, 13, 17, 22, 25, 26, 31, 37, 38, 42, 48, 53, 55, 59, 65, 67,
       72, 76, 80, 84, 88, 92, 99])

In [560]:
arr.prod()

26011238400000

In [561]:
arr.cumprod()

array([             1,              5,             35,            140,
                  700,           2100,           2100,          10500,
                63000,          63000,         252000,        1512000,
              7560000,       15120000,       60480000,      362880000,
            725760000,     3628800000,    14515200000,    58060800000,
         232243200000,   928972800000,  3715891200000, 26011238400000])

In [562]:
arr.ptp()

6

In [567]:
arr.argmin()

0

In [568]:
arr.argmax()

2

### 1.4 Introducing `axis`

In [570]:
arr

array([[1, 5, 7],
       [4, 5, 3],
       [1, 5, 6],
       [1, 4, 6],
       [5, 2, 4],
       [6, 2, 5],
       [4, 4, 4],
       [4, 4, 7]])

In [572]:
print(arr.max()) # <--- Among all
print(arr.max(axis=0)) # <--- Among columns
print(arr.max(axis=1)) # <--- Among rows

7
[6 5 7]
[7 5 6 6 5 6 4 7]


In [574]:
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

1
[1 2 3]
[1 3 1 1 2 2 4 4]


In [576]:
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

4.125
[3.25  3.875 5.25 ]
[4.33333333 4.         4.         3.66666667 3.66666667 4.33333333
 4.         5.        ]


In [578]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

99
[26 31 42]
[13 12 12 11 11 13 12 15]


In [580]:
print(arr.cumsum())

[ 1  6 13 17 22 25 26 31 37 38 42 48 53 55 59 65 67 72 76 80 84 88 92 99]


In [581]:
print(arr.cumsum(axis=0))

[[ 1  5  7]
 [ 5 10 10]
 [ 6 15 16]
 [ 7 19 22]
 [12 21 26]
 [18 23 31]
 [22 27 35]
 [26 31 42]]


In [582]:
print(arr.cumsum(axis=1))

[[ 1  6 13]
 [ 4  9 12]
 [ 1  6 12]
 [ 1  5 11]
 [ 5  7 11]
 [ 6  8 13]
 [ 4  8 12]
 [ 4  8 15]]


In [584]:
print(arr.prod())
print(arr.prod(axis=0))
print(arr.prod(axis=1))

26011238400000
[  1920  32000 423360]
[ 35  60  30  24  40  60  64 112]


In [586]:
arr.cumprod()

array([             1,              5,             35,            140,
                  700,           2100,           2100,          10500,
                63000,          63000,         252000,        1512000,
              7560000,       15120000,       60480000,      362880000,
            725760000,     3628800000,    14515200000,    58060800000,
         232243200000,   928972800000,  3715891200000, 26011238400000])

In [587]:
arr.cumprod(axis=0)

array([[     1,      5,      7],
       [     4,     25,     21],
       [     4,    125,    126],
       [     4,    500,    756],
       [    20,   1000,   3024],
       [   120,   2000,  15120],
       [   480,   8000,  60480],
       [  1920,  32000, 423360]])

In [588]:
arr.cumprod(axis=1)

array([[  1,   5,  35],
       [  4,  20,  60],
       [  1,   5,  30],
       [  1,   4,  24],
       [  5,  10,  40],
       [  6,  12,  60],
       [  4,  16,  64],
       [  4,  16, 112]])

In [589]:
print(arr.ptp())
print(arr.ptp(axis=0))
print(arr.ptp(axis=1))

6
[5 3 4]
[6 2 5 5 3 4 0 3]


In [590]:
print(arr.std())
print(arr.std(axis=0))
print(arr.std(axis=1))

1.7154324041865752
[1.85404962 1.16592238 1.39194109]
[2.49443826 0.81649658 2.1602469  2.05480467 1.24721913 1.69967317
 0.         1.41421356]


In [591]:
print(arr.var())
print(arr.var(axis=0))
print(arr.var(axis=1))

2.9427083333333335
[3.4375   1.359375 1.9375  ]
[6.22222222 0.66666667 4.66666667 4.22222222 1.55555556 2.88888889
 0.         2.        ]


In [592]:
print(arr.argmin())
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))

0
[0 4 1]
[0 2 0 0 1 1 0 0]


In [593]:
print(arr.argmax())
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))

2
[5 0 0]
[2 1 2 2 0 0 0 2]


In [594]:
arr.argsort()

array([[0, 1, 2],
       [2, 0, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [595]:
arr.argsort(axis=0)

array([[0, 4, 1],
       [2, 5, 4],
       [3, 3, 6],
       [1, 6, 5],
       [6, 7, 2],
       [7, 0, 3],
       [4, 1, 0],
       [5, 2, 7]])

In [596]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [2, 0, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [598]:
# 3 dimensions
arr = np.random.randint(1,100,size=(4,3,5))
arr

array([[[73, 47, 10, 88, 90],
        [72,  5, 13, 86, 34],
        [25, 23, 85,  3,  8]],

       [[46, 62, 39, 51, 22],
        [45, 75, 23, 49, 80],
        [51, 28, 99, 29, 59]],

       [[70, 78, 93, 28, 74],
        [47,  4, 88,  2, 64],
        [29, 89, 95, 47, 15]],

       [[38, 97, 49, 72, 40],
        [16, 34,  6, 87, 53],
        [21, 99, 29, 99,  2]]])

In [599]:
arr.mean()

49.75

In [601]:
arr.mean(axis=0)

array([[56.75, 71.  , 47.75, 59.75, 56.5 ],
       [45.  , 29.5 , 32.5 , 56.  , 57.75],
       [31.5 , 59.75, 77.  , 44.5 , 21.  ]])

In [602]:
arr.mean(axis=1)

array([[56.66666667, 25.        , 36.        , 59.        , 44.        ],
       [47.33333333, 55.        , 53.66666667, 43.        , 53.66666667],
       [48.66666667, 57.        , 92.        , 25.66666667, 51.        ],
       [25.        , 76.66666667, 28.        , 86.        , 31.66666667]])

In [603]:
arr.mean(axis=2)

array([[61.6, 42. , 28.8],
       [44. , 54.4, 53.2],
       [68.6, 41. , 55. ],
       [59.2, 39.2, 50. ]])

### 1.5 Filtering

In [604]:
np.random.seed(123)
arr = np.random.randn(20)
arr

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ,
       -0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196,
       -0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ])

In [608]:
mask = arr > 0
mask

array([False,  True,  True, False, False,  True, False, False,  True,
       False, False, False,  True, False, False, False,  True,  True,
        True,  True])

In [609]:
arr[mask]

array([0.99734545, 0.2829785 , 1.65143654, 1.26593626, 1.49138963,
       2.20593008, 2.18678609, 1.0040539 , 0.3861864 ])

In [610]:
# is the same with
mask = []
for e in arr:
    mask.append(e > 0)
mask = np.array(mask)
mask

array([False,  True,  True, False, False,  True, False, False,  True,
       False, False, False,  True, False, False, False,  True,  True,
        True,  True])

In [611]:
arr[mask]

array([0.99734545, 0.2829785 , 1.65143654, 1.26593626, 1.49138963,
       2.20593008, 2.18678609, 1.0040539 , 0.3861864 ])

In [612]:
~mask

array([ True, False, False,  True,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False])

In [613]:
arr[~mask]

array([-1.0856306 , -1.50629471, -0.57860025, -2.42667924, -0.42891263,
       -0.8667404 , -0.67888615, -0.09470897, -0.638902  , -0.44398196,
       -0.43435128])

In [614]:
mask = (arr > 0) & (arr < 1.5)
mask

array([False,  True,  True, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True])

In [616]:
arr[mask]

array([0.99734545, 0.2829785 , 1.26593626, 1.49138963, 1.0040539 ,
       0.3861864 ])

In [617]:
mask = (arr <= 0) | (arr >= 1.5)
mask

array([ True, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False])

In [618]:
np.random.seed(123)
arr = np.random.randint(20,size=(20,3))
arr

array([[13,  2,  2],
       [ 6, 17, 19],
       [10,  1,  0],
       [17, 15,  9],
       [ 0, 14,  0],
       [15, 19, 14],
       [ 4,  0, 16],
       [ 4, 17,  3],
       [ 2,  7,  2],
       [15, 16,  7],
       [ 9,  3,  6],
       [ 1,  2,  1],
       [12,  8,  3],
       [10,  5,  0],
       [11,  2, 10],
       [13, 18,  4],
       [15, 11, 12],
       [ 6, 13, 19],
       [16,  6, 14],
       [ 7, 11,  7]])

In [619]:
mask = (arr[:,0] == 4) | (arr[:,0] == 15)
mask

array([False, False, False, False, False,  True,  True,  True, False,
        True, False, False, False, False, False, False,  True, False,
       False, False])

In [620]:
arr[mask]

array([[15, 19, 14],
       [ 4,  0, 16],
       [ 4, 17,  3],
       [15, 16,  7],
       [15, 11, 12]])

In [621]:
arr[arr > 5]

array([13,  6, 17, 19, 10, 17, 15,  9, 14, 15, 19, 14, 16, 17,  7, 15, 16,
        7,  9,  6, 12,  8, 10, 11, 10, 13, 18, 15, 11, 12,  6, 13, 19, 16,
        6, 14,  7, 11,  7])

## Section 2: Functions

### 2.1 Array Creation

In [623]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [626]:
np.arange(6,2,-1)

array([6, 5, 4, 3])

In [627]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [630]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [631]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [633]:
np.logspace(2.0, 3.0, num=5, base = 11)

array([ 121.        ,  220.36039471,  401.31159963,  730.8527479 ,
       1331.        ])

In [634]:
np.logspace(2.0, 3.0, num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [636]:
np.logspace(2.0, 3.0, num=5, dtype = int)

array([ 100,  177,  316,  562, 1000])

In [637]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [639]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [643]:
np.zeros_like(arr).shape

(20, 3)

In [646]:
np.zeros_like(arr, float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [647]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [648]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [649]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [650]:
np.empty((5,3))

array([[56.75, 71.  , 47.75],
       [59.75, 56.5 , 45.  ],
       [29.5 , 32.5 , 56.  ],
       [57.75, 31.5 , 59.75],
       [77.  , 44.5 , 21.  ]])

In [654]:
np.empty_like(arr)

array([[            45259584,             45299136,      140441388755744],
       [     140441386305880, -7639770098424896979,      140441443687024],
       [     140441417527368,  4361956535841746873,      140441443636144],
       [     140441443645544, -6533595444362324073,      140441423209056],
       [     140441417157672,  2740468096275663580,      140441443651888],
       [            40976040,  7665521562941898243,      140441415578208],
       [            39527608, -2704784650984465026,      140441443612744],
       [            41684232,  1736525720293259129,      140441443636272],
       [     140441415562920,  6511489717008137612,      140441443636336],
       [     140441415563736,  3589390443932372836,      140441417482032],
       [     140441415563872, -3280758634162432895,      140441417482096],
       [     140441415564008, -7547422202672158015,      140441443647648],
       [     140441417484760,  3683805027637434995,      140441422484584],
       [     140441415562

In [655]:
np.full((10,3),-3)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [656]:
arr20 = np.arange(10).reshape(2, 5)
np.full_like(arr20, 10.0)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [657]:
arr21 = np.arange(10, dtype = float).reshape(2, 5)
np.full_like(arr21, 0.01)

array([[0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01]])

In [658]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [659]:
np.identity(2, dtype = float)

array([[1., 0.],
       [0., 1.]])

In [660]:
np.identity(2, dtype = int)

array([[1, 0],
       [0, 1]])

### 2.2 Array Manipulation

In [661]:
arr = np.random.randint(0,100,size=(3,5))
print(arr)

[[ 1 43 58 55 25]
 [50 84 56 49 12]
 [18 81  1 51 44]]


In [662]:
print(np.ravel(arr))

[ 1 43 58 55 25 50 84 56 49 12 18 81  1 51 44]


In [664]:
arr1 = np.arange(0,10)
arr2 = np.linspace(-5,4,10,dtype=int)
np.column_stack([arr1,arr2])

array([[ 0, -5],
       [ 1, -4],
       [ 2, -3],
       [ 3, -2],
       [ 4, -1],
       [ 5,  0],
       [ 6,  1],
       [ 7,  2],
       [ 8,  3],
       [ 9,  4]])

In [665]:
np.row_stack([arr1,arr2])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [666]:
np.vstack([arr1,arr2]) # !

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [667]:
np.hstack([arr1,arr2]) # !

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -5, -4, -3, -2, -1,  0,  1,
        2,  3,  4])

In [668]:
arr1.reshape((-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [669]:
np.vstack([arr1.reshape((-1,1)),arr2.reshape((-1,1))])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [670]:
np.hstack([arr1.reshape((-1,1)),arr2.reshape((-1,1))])

array([[ 0, -5],
       [ 1, -4],
       [ 2, -3],
       [ 3, -2],
       [ 4, -1],
       [ 5,  0],
       [ 6,  1],
       [ 7,  2],
       [ 8,  3],
       [ 9,  4]])

In [671]:
np.concatenate((arr1,arr2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -5, -4, -3, -2, -1,  0,  1,
        2,  3,  4])

In [672]:
np.concatenate((arr1.reshape((-1,1)),arr2.reshape((-1,1))))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [673]:
np.append(arr1,-123)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, -123])

In [674]:
np.append(arr1,arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -5, -4, -3, -2, -1,  0,  1,
        2,  3,  4])

In [676]:
np.append(arr1,arr2.reshape((-1,1)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -5, -4, -3, -2, -1,  0,  1,
        2,  3,  4])

In [677]:
np.insert(arr1,0,-123)

array([-123,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [678]:
np.insert(arr1,0,arr2)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [679]:
arr

array([[ 1, 43, 58, 55, 25],
       [50, 84, 56, 49, 12],
       [18, 81,  1, 51, 44]])

In [681]:
np.flip(arr)

array([[44, 51,  1, 81, 18],
       [12, 49, 56, 84, 50],
       [25, 55, 58, 43,  1]])

In [682]:
np.flip(arr,axis=0)

array([[18, 81,  1, 51, 44],
       [50, 84, 56, 49, 12],
       [ 1, 43, 58, 55, 25]])

In [683]:
np.flip(arr,axis=1)

array([[25, 55, 58, 43,  1],
       [12, 49, 56, 84, 50],
       [44, 51,  1, 81, 18]])

In [685]:
arr

array([[ 1, 43, 58, 55, 25],
       [50, 84, 56, 49, 12],
       [18, 81,  1, 51, 44]])

In [684]:
np.roll(arr,1,axis=0)

array([[18, 81,  1, 51, 44],
       [ 1, 43, 58, 55, 25],
       [50, 84, 56, 49, 12]])

In [686]:
np.roll(arr,2,axis=0)

array([[50, 84, 56, 49, 12],
       [18, 81,  1, 51, 44],
       [ 1, 43, 58, 55, 25]])

In [687]:
np.roll(arr,1,axis=1)

array([[25,  1, 43, 58, 55],
       [12, 50, 84, 56, 49],
       [44, 18, 81,  1, 51]])

In [688]:
arr

array([[ 1, 43, 58, 55, 25],
       [50, 84, 56, 49, 12],
       [18, 81,  1, 51, 44]])

In [689]:
np.sort(arr,axis=0)

array([[ 1, 43,  1, 49, 12],
       [18, 81, 56, 51, 25],
       [50, 84, 58, 55, 44]])

In [690]:
np.sort(arr,axis=1)

array([[ 1, 25, 43, 55, 58],
       [12, 49, 50, 56, 84],
       [ 1, 18, 44, 51, 81]])

In [691]:
np.sort(arr,axis=-1)

array([[ 1, 25, 43, 55, 58],
       [12, 49, 50, 56, 84],
       [ 1, 18, 44, 51, 81]])

In [693]:
mask = np.argsort(arr[:,0])
mask

array([0, 2, 1])

In [695]:
arr[mask]

array([[ 1, 43, 58, 55, 25],
       [18, 81,  1, 51, 44],
       [50, 84, 56, 49, 12]])

In [696]:
np.argsort(arr)

array([[0, 4, 1, 3, 2],
       [4, 3, 0, 2, 1],
       [2, 0, 4, 3, 1]])

In [697]:
np.argsort(arr,axis=0)

array([[0, 0, 2, 1, 1],
       [2, 2, 1, 2, 0],
       [1, 1, 0, 0, 2]])

In [698]:
np.argsort(arr,axis=1)

array([[0, 4, 1, 3, 2],
       [4, 3, 0, 2, 1],
       [2, 0, 4, 3, 1]])

### 2.3 Mathematical

In [699]:
arr = np.array([1,-1,0.1])

In [700]:
np.arccos(arr)

array([0.        , 3.14159265, 1.47062891])

In [701]:
np.arccosh(np.arange(10))

/home/candar/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccosh
  """Entry point for launching an IPython kernel.


array([       nan, 0.        , 1.3169579 , 1.76274717, 2.06343707,
       2.29243167, 2.47788873, 2.63391579, 2.76865938, 2.88727095])

In [702]:
arr = [4,-5,6,-7]
print(np.absolute(arr))
print(np.abs(arr))

[4 5 6 7]
[4 5 6 7]


In [706]:
np.prod(arr)

840

In [707]:
arr = [1273.5538, 211.33354, 103.7163]
np.round(arr)

array([1274.,  211.,  104.])

In [708]:
np.round(arr, decimals = 2)

array([1273.55,  211.33,  103.72])

In [710]:
np.round(arr, decimals = -2)

array([1300.,  200.,  100.])

In [712]:
d = [
    [14, 17, 12, 33, 44],
    [15, 6, 27, 8, 19],  
    [23, 2, 54, 1, 4]
]
arr = np.array(d)
   
print(np.sum(arr)) 
print(np.sum(arr, dtype = np.int32))
print(np.sum(arr, dtype = np.float32))
print(np.sum(arr, axis = 0)) 
print(np.sum(arr, axis = 1))

279
279
279.0
[52 25 93 42 67]
[120  75  84]


In [714]:
d = [1, 3, 5, 2**3, np.e]
np.log(d)

array([0.        , 1.09861229, 1.60943791, 2.07944154, 1.        ])

In [715]:
np.log2(d)

array([0.        , 1.5849625 , 2.32192809, 3.        , 1.44269504])

In [717]:
np.log10(d)

array([0.        , 0.47712125, 0.69897   , 0.90308999, 0.43429448])

In [719]:
d = [0, 1, 3, 5, 2**3]
np.log1p(d)

array([0.        , 0.69314718, 1.38629436, 1.79175947, 2.19722458])

In [723]:
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [720]:
np.exp(b)

array([[ 2.71828183,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 , 20.08553692]])

In [722]:
np.e**2

7.3890560989306495

In [724]:
np.count_nonzero(arr)

15

### 2.4 Logical

In [725]:
arr = np.random.randint(0,100,size=(10,5))
arr

array([[48, 56, 91, 49, 86],
       [ 3, 67, 11, 21, 89],
       [98,  3, 11,  3, 94],
       [ 6,  9, 87, 14, 83],
       [70, 12, 54, 27, 38],
       [17, 61, 74, 99, 99],
       [65, 47, 16,  5, 86],
       [46, 15, 59, 40, 25],
       [45, 49,  0, 35, 29],
       [ 1, 83, 68, 30,  7]])

In [727]:
np.array_equal(arr,arr)

True

In [728]:
np.array_equal(arr,arr*1.0)

True

In [729]:
arr == arr

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [730]:
(arr == arr).all()

True

In [731]:
arr > 30

array([[ True,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [False, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True, False],
       [False,  True,  True, False, False]])

In [732]:
arr[arr > 30]

array([48, 56, 91, 49, 86, 67, 89, 98, 94, 87, 83, 70, 54, 38, 61, 74, 99,
       99, 65, 47, 86, 46, 59, 40, 45, 49, 35, 83, 68])

In [736]:
np.any([-1, 0, 5]) # Are there any item that are not equal to zero?

True

In [737]:
np.any([0,0,0])

False

In [738]:
np.any([[True, False], [True, True]])

True

In [739]:
np.any([[False, False], [False, False]], axis=0)

array([False, False])

In [740]:
np.all([[False, False], [False, False]], axis=0)

array([False, False])

In [741]:
arr = np.arange(20,dtype=float).reshape(5, 4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [742]:
np.isfinite(arr)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [744]:
arr1 = arr.copy()
arr1[2,3] = np.inf
arr1[1,3] = np.nan

In [745]:
np.isfinite(arr1)

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [746]:
np.isinf(arr1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [747]:
print(np.isinf(1))
print(np.isinf(0))
print(np.isinf(np.nan))
print(np.isinf(np.inf))
print(np.isinf(np.NINF))

False
False
False
True
True


In [749]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [750]:
row_idx, col_idx = np.where(arr < 8)

In [751]:
row_idx

array([0, 0, 0, 0, 1, 1, 1, 1])

In [752]:
col_idx

array([0, 1, 2, 3, 0, 1, 2, 3])

In [753]:
arr[row_idx,col_idx]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [755]:
d = [
    [0,1,1,10],
    [0.1,0,1,0],
    [10,1,0,1],
    [1,0,10,1.0]
]
arr = np.array(d)
row_idx, col_idx = np.nonzero(arr)

In [756]:
row_idx

array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3])

In [757]:
col_idx

array([1, 2, 3, 0, 2, 0, 1, 3, 0, 2, 3])

### 2.5 Random Number Generation

In [758]:
np.random.randint(0,10)

6

In [759]:
np.random.randint(1,10,size=(3,2,4))

array([[[2, 5, 4, 4],
        [8, 7, 9, 7]],

       [[5, 5, 8, 1],
        [1, 9, 9, 5]],

       [[9, 7, 2, 7],
        [9, 8, 2, 8]]])

In [760]:
np.random.uniform(-1,1,size=5)

array([-0.23032438, -0.36642421, -0.29147065, -0.65783634,  0.65822527])

In [761]:
np.random.rand(4,3)

array([[0.33867085, 0.55237008, 0.57855147],
       [0.52153306, 0.00268806, 0.98834542],
       [0.90534158, 0.20763586, 0.29248941],
       [0.52001015, 0.90191137, 0.98363088]])

In [762]:
np.random.randn(4,3)

array([[ 0.42614664, -1.60540974, -0.4276796 ],
       [ 1.24286955, -0.73521696,  0.50124899],
       [ 1.01273905,  0.27874086, -1.37094847],
       [-0.33247528,  1.95941134, -2.02504576]])

In [763]:
np.random.normal(3,1.5,size=(4,3))

array([[2.58632098, 2.17183789, 3.18112104],
       [4.12232343, 5.41303645, 2.59465141],
       [4.21851199, 3.74961022, 3.71152095],
       [2.1541141 , 1.5040178 , 1.34993533]])

In [764]:
np.random.exponential(0.1,size=(6,2))

array([[0.10944055, 0.01180993],
       [0.10932441, 0.21879786],
       [0.1191752 , 0.05804042],
       [0.0576635 , 0.14485788],
       [0.08338862, 0.00887265],
       [0.08738806, 0.1686555 ]])

In [765]:
np.random.poisson(5,size=20)

array([7, 3, 4, 3, 7, 4, 6, 5, 6, 6, 3, 4, 4, 6, 6, 4, 4, 2, 4, 4])

In [766]:
arr

array([[ 0. ,  1. ,  1. , 10. ],
       [ 0.1,  0. ,  1. ,  0. ],
       [10. ,  1. ,  0. ,  1. ],
       [ 1. ,  0. , 10. ,  1. ]])

In [769]:
np.random.choice(arr.ravel(),size=3)

array([10. , 10. ,  0.1])

In [770]:
np.random.shuffle(arr)

In [771]:
arr

array([[ 1. ,  0. , 10. ,  1. ],
       [ 0.1,  0. ,  1. ,  0. ],
       [ 0. ,  1. ,  1. , 10. ],
       [10. ,  1. ,  0. ,  1. ]])

### 2.6 Linear Algebra

In [772]:
arr = np.array([[1, 21, 30], 
                [63 ,434, 3], 
                [54, 54, 56]])
arr

array([[  1,  21,  30],
       [ 63, 434,   3],
       [ 54,  54,  56]])

In [773]:
arr * arr # element-wise

array([[     1,    441,    900],
       [  3969, 188356,      9],
       [  2916,   2916,   3136]])

In [774]:
m = np.matrix(arr)
m

matrix([[  1,  21,  30],
        [ 63, 434,   3],
        [ 54,  54,  56]])

In [775]:
m * m # matrix multiplication!

matrix([[  2944,  10755,   1773],
        [ 27567, 189841,   3360],
        [  6480,  27594,   4918]])

In [777]:
arr

array([[  1,  21,  30],
       [ 63, 434,   3],
       [ 54,  54,  56]])

In [776]:
np.diag(arr)

array([  1, 434,  56])

In [778]:
np.diag(arr, 1)

array([21,  3])

In [779]:
np.diag(arr, 2)

array([30])

In [780]:
np.diag(arr, -1)

array([63, 54])

In [781]:
np.trace(arr)

491

In [782]:
arr_inv = np.linalg.inv(arr)
arr_inv

array([[-0.03728126, -0.00068565,  0.02000883],
       [ 0.00519794,  0.00241521, -0.002914  ],
       [ 0.03093748, -0.00166779,  0.00137284]])

In [783]:
arr * arr_inv

array([[-0.03728126, -0.01439858,  0.60026499],
       [ 0.32747033,  1.0481991 , -0.00874199],
       [ 1.67062406, -0.0900606 ,  0.07687889]])

In [784]:
np.dot(arr,arr_inv)

array([[ 1.00000000e+00,  7.37257477e-18, -4.33680869e-19],
       [-3.46944695e-18,  1.00000000e+00,  4.05491613e-17],
       [-2.49800181e-16,  4.33680869e-17,  1.00000000e+00]])

In [785]:
np.matmul(arr,arr_inv)

array([[ 1.00000000e+00,  7.37257477e-18, -4.33680869e-19],
       [-3.46944695e-18,  1.00000000e+00,  4.05491613e-17],
       [-2.49800181e-16,  4.33680869e-17,  1.00000000e+00]])

In [786]:
np.linalg.det(arr)

-647563.9999999998

In [787]:
np.linalg.matrix_rank(arr)

3

In [791]:
arr1 = np.random.randn(5,3)
arr1 = np.hstack([arr1,(arr1[:,2] + np.random.randn(5)/5).reshape((-1,1))])
arr1

array([[ 0.36233741,  0.42804609,  0.03647452,  0.46190933],
       [-0.56285652, -0.03664065,  2.93214489,  2.83424753],
       [ 1.81095662,  1.17887773,  0.27788677,  0.40337779],
       [ 0.68631345, -0.24897077, -1.63503755, -1.69974583],
       [-1.4766429 , -0.87617199, -0.21624005, -0.57823772]])

In [792]:
np.linalg.matrix_rank(arr1)

4

In [789]:
arr1 = np.random.randn(5,3)
arr1 = np.hstack([arr1,(arr1[:,2]*1.5).reshape((-1,1))])
arr1

array([[ 1.34269498, -0.90506318,  0.33897486,  0.50846229],
       [ 0.09301208, -0.95940738, -0.82691461, -1.24037192],
       [-0.00978792, -0.53441959,  1.18570843,  1.77856264],
       [-1.45566731,  0.74339145, -0.32353374, -0.48530061],
       [-0.46197074,  0.26114286,  0.66685237,  1.00027855]])

In [790]:
np.linalg.matrix_rank(arr1)

3

In [793]:
np.linalg.eig(arr)

(array([438.12192193, -20.220022  ,  73.09810007]),
 array([[-0.05756868, -0.8469722 ,  0.36536438],
        [-0.98736051,  0.11404488, -0.07149395],
        [-0.14766537,  0.51926088,  0.92811502]]))

In [794]:
np.linalg.svd(arr)

(array([[-0.04899023,  0.3068272 , -0.95050356],
        [-0.98851648, -0.15109747,  0.00217446],
        [-0.1429515 ,  0.93969496,  0.31070605]]),
 array([443.50722921,  74.57912535,  19.57783698]),
 array([[-0.15793409, -0.98705116, -0.02805037],
        [ 0.55687452, -0.11248996,  0.82294397],
        [ 0.81544319, -0.11435037, -0.56742964]]))

In [795]:
np.linalg.svd(arr1)

(array([[ 0.06986107, -0.20028837,  0.5696982 , -0.57819685,  0.54418413],
        [ 0.85236051,  0.08539244, -0.4430082 , -0.18911358,  0.18484991],
        [ 0.07256003, -0.75461071, -0.08131577,  0.53398569,  0.36543774],
        [-0.50466007, -0.10446607, -0.68674809, -0.40163282,  0.31854856],
        [-0.09302822,  0.61011656,  0.0308627 ,  0.4283396 ,  0.65929979]]),
 array([4.81569   , 2.89415542, 0.43346652, 0.23854553]),
 array([[-0.1104776 ,  0.06050357,  0.69921667,  0.70372585],
        [-0.84992798, -0.5137987 ,  0.02496602, -0.11406147],
        [-0.48073831,  0.71093612, -0.42586027,  0.28653717],
        [-0.18522366,  0.47636126,  0.57368613, -0.64004403]]))

In [798]:
a = np.array([0,1,2,3])
b = np.linspace(-1, 2, 4)
print(a)
print(b)

[0 1 2 3]
[-1.  0.  1.  2.]


In [799]:
np.inner(a,b)

8.0

In [800]:
np.outer(a, b)

array([[-0.,  0.,  0.,  0.],
       [-1.,  0.,  1.,  2.],
       [-2.,  0.,  2.,  4.],
       [-3.,  0.,  3.,  6.]])

### 2.7 Statistics

In [801]:
arr

array([[  1,  21,  30],
       [ 63, 434,   3],
       [ 54,  54,  56]])

In [802]:
np.min(arr)

1

In [803]:
np.min(arr,axis=0)

array([ 1, 21,  3])

In [804]:
np.min(arr,axis=1)

array([ 1,  3, 54])

In [805]:
np.max(arr)

434

In [806]:
np.max(arr,axis=0)

array([ 63, 434,  56])

In [807]:
np.max(arr,axis=1)

array([ 30, 434,  56])

In [808]:
arr = [20, 2, 7, 1, 34]

np.mean(arr)

12.8

In [809]:
d = [
    [14, 17, 12, 33, 44],  
    [15, 6, 27, 8, 19], 
    [23, 2, 54, 1, 4, ]
]
arr = np.array(d)
    
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


In [811]:
np.median(arr)

15.0

In [812]:
print(np.median(arr)) 
print(np.median(arr, axis = 0)) 
print(np.median(arr, axis = 1))

15.0
[15.  6. 27.  8. 19.]
[17. 15.  4.]


In [813]:
num1 = 6
num2 = 4
    
np.mod(num1, num2)

2

In [814]:
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [815]:
np.mod(arr,2) # remainder of division

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0]])

In [816]:
np.mod(arr,10)

array([[4, 7, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [3, 2, 4, 1, 4]])

In [817]:
arr40 = np.array([2, -4, 7])
arr41 = np.array([2, 3, 4])
    
np.mod(arr40, arr41)

array([0, 2, 3])

In [819]:
arr42 = np.array([[20, 15, 37], [47, 13, np.nan]]) 
    
print(np.mean(arr42))
print(np.nanmean(arr42))

nan
26.4


In [820]:
arr43 = np.array([[32, 20, 24], 
                  [47, 63, np.nan],   
                  [17, 28, np.nan],
                  [10, 8, 9]]) 
    
    
print(np.mean(arr43, axis = 0)) 
print(np.nanmean(arr43, axis = 0)) 

[26.5  29.75   nan]
[26.5  29.75 16.5 ]


In [821]:
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [822]:
np.cumsum(arr)

array([ 14,  31,  43,  76, 120, 135, 141, 168, 176, 195, 218, 220, 274,
       275, 279])

In [823]:
np.cumsum(arr,axis=0)

array([[14, 17, 12, 33, 44],
       [29, 23, 39, 41, 63],
       [52, 25, 93, 42, 67]])

In [824]:
np.cumsum(arr,axis=1)

array([[ 14,  31,  43,  76, 120],
       [ 15,  21,  48,  56,  75],
       [ 23,  25,  79,  80,  84]])

In [826]:
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [827]:
np.diff(arr[0])

array([ 3, -5, 21, 11])

In [828]:
np.diff(arr,axis=0)

array([[  1, -11,  15, -25, -25],
       [  8,  -4,  27,  -7, -15]])

In [829]:
np.diff(arr,axis=1)

array([[  3,  -5,  21,  11],
       [ -9,  21, -19,  11],
       [-21,  52, -53,   3]])

In [831]:
np.diff(arr,2,axis=1)

array([[  -8,   26,  -10],
       [  30,  -40,   30],
       [  73, -105,   56]])

In [832]:
np.cumprod(arr)

array([               14,               238,              2856,
                   94248,           4146912,          62203680,
               373222080,       10076996160,       80615969280,
           1531703416320,    35229178575360,    70458357150720,
        3804751286138880,  3804751286138880, 15219005144555520])

In [834]:
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

15.0
7.0
25.0


In [835]:
print(np.percentile(arr, 50))
print(np.percentile(arr, 0))
print(np.percentile(arr, 50, axis =0))
print(np.percentile(arr, 0, axis =0))

15.0
1.0
[15.  6. 27.  8. 19.]
[14.  2. 12.  1.  4.]


In [836]:
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [838]:
print(np.quantile(arr, 0.2))
print(np.quantile(arr, 0.5))
print(np.quantile(arr, 0.9, axis =0))
print(np.quantile(arr, 0, axis =0))

5.6000000000000005
15.0
[21.4 14.8 48.6 28.  39. ]
[14  2 12  1  4]


In [840]:
hist, bins = np.histogram(arr, bins = 5)
print(hist) 
print(bins) 

[5 5 2 1 2]
[ 1.  11.6 22.2 32.8 43.4 54. ]


In [842]:
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [843]:
np.corrcoef(arr)

array([[ 1.        , -0.13508605, -0.63673729],
       [-0.13508605,  1.        ,  0.8277841 ],
       [-0.63673729,  0.8277841 ,  1.        ]])

In [845]:
# linear fit
x = np.random.uniform(0,50,size=40)
y = x * 3 + np.random.randn(40)

np.polyfit(x,y,deg=1)

array([2.98706208, 0.46742813])

In [847]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8 ])
np.clip(arr,2,6)

array([2, 2, 3, 4, 5, 6, 6, 6])

In [848]:
d = [
    [14, 17, 12, 33, 44],  
    [15, 6, 27, 8, 19], 
    [23, 2, 54, 1, 4,]
]
arr = np.array(d)

print(np.ptp(arr)) 
print(np.ptp(arr, axis = 0)) 
print(np.ptp(arr, axis = 1))

53
[ 9 15 42 32 40]
[32 21 53]


In [849]:
arr = [[2, 2, 2, 2, 2],  
         [15, 6, 27, 8, 2], 
         [23, 2, 54, 1, 2, ], 
         [11, 44, 34, 7, 2]] 

print(np.std(arr)) 
print(np.std(arr, axis = 0)) 
print(np.std(arr, axis = 1))

15.3668474320532
[ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]
[ 0.          8.7772433  20.53874388 16.40243884]


In [850]:
print(np.var(arr)) 
print(np.var(arr, axis = 0)) 
print(np.var(arr, axis = 1))

236.14000000000004
[ 57.1875 312.75   345.6875   9.25     0.    ]
[  0.    77.04 421.84 269.04]


In [851]:
arr

[[2, 2, 2, 2, 2], [15, 6, 27, 8, 2], [23, 2, 54, 1, 2], [11, 44, 34, 7, 2]]

In [856]:
np.apply_along_axis(str,0,arr)

array(['[ 2 15 23 11]', '[ 2  6  2 44]', '[ 2 27 54 34]', '[2 8 1 7]',
       '[2 2 2 2]'], dtype='<U13')

In [857]:
np.apply_along_axis(str,1,arr)

array(['[2 2 2 2 2]', '[15  6 27  ', '[23  2 54  ', '[11 44 34  '],
      dtype='<U11')

In [858]:
np.apply_along_axis(lambda x: x**2 - 3,0,arr)

array([[   1,    1,    1,    1,    1],
       [ 222,   33,  726,   61,    1],
       [ 526,    1, 2913,   -2,    1],
       [ 118, 1933, 1153,   46,    1]])

## Example Project

**Numerical Integration**

![](https://ars.els-cdn.com/content/image/3-s2.0-B9780750667227500357-f04-02-9780750667227.gif)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Riemann_sum_convergence.png/300px-Riemann_sum_convergence.png)

In [859]:
# plain python
def area_under_curve(f,l,u,n=10000):
    "Compute Riemann sum for numerical integration."
    tot = 0
    h = (u - l) / n
    x = l + h/2
    for i in range(n):
        tot += f(x) * h
        x += h
    return tot

In [861]:
f = lambda x: 5*x**2 - 2
area_under_curve(f,-2,2)

18.666666399996572

In [862]:
%timeit area_under_curve(f,-2,2)

2.72 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [863]:
# numpy
def area_under_curve(f,lower,upper,n=10000):
    "Compute Riemann sum for numerical integration."
    h = (upper - lower) / n
    bins = np.linspace(lower + h/2,upper - h/2,n)
    out = f(bins) * h
    return out.sum()

In [864]:
f = lambda x: 5*x**2 - 2
area_under_curve(f,-2,2)

18.666666400000004

In [865]:
%timeit area_under_curve(f,-2,2)

140 µs ± 6.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Project

![](http://cdn.shopify.com/s/files/1/0684/5947/articles/morpheus-red-pill-blue-pill_1024x1024.jpg?v=1536175294)



<span style="color:blue">**Matrix Inverse: Gauss-Jordan Elimination**</span> [see more](https://online.stat.psu.edu/statprogram/reviews/matrix-algebra/gauss-jordan-elimination#:~:text=Gauss%2DJordan%20Elimination%20is%20an,rows%20by%20a%20nonzero%20scalar.)

<span style="color:red">**Optimization: Ordinary Least Squares**</span> [see more](https://www.codesansar.com/numerical-methods/linear-regression-method-algorithm.htm)

## Summary

* Arrays
    * Broadcasting
    * Axes
* Functions
    * Array Manipulation
    * Linear Algebra
    * Statistics

## Next Week

Visualization with `matplotlib`

## References

https://en.wikipedia.org/wiki/Array_programming

https://numpy.org/devdocs/user/theory.broadcasting.html

https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html