# Chapter 4

@Mert

## Learning Goals

- `numpy` arrays
- `numpy` basics
- vectoral computation


## Authors

- Mert Candar, mccandar@gmail.com
- Aras Kahraman, aras.kahraman@hotmail.com

## Learning Curve Boosters

https://github.com/kyclark/tiny_python_projects

https://github.com/Python-World/python-mini-projects/tree/master/projects

https://github.com/rlvaugh/Impractical_Python_Projects

## An Introduction to `numpy`

The module `numpy` is a handy and comprehensive numerical computation library. @Mert

### `numpy` Arrays

@Mert

In [2]:
import numpy as np

In [9]:
d = [4,5,6,7]
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [10]:
type(arr)

numpy.ndarray

In [11]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [12]:
d = (4,5,6,7)
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [14]:
d = range(5)
arr = np.array(d)
arr

array([0, 1, 2, 3, 4])

In [17]:
d = [4,5,6,7]
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [18]:
arr.shape

(4,)

In [20]:
arr.ndim

1

In [21]:
d = [
    [4,5,6,7],
    [4,5,6,7],
    [4,5,6,7],
    [4,5,6,7],
]
arr = np.array(d)
arr

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [22]:
arr.shape

(4, 4)

In [23]:
arr.ndim

2

In [24]:
np.abs

<ufunc 'absolute'>

In [25]:
np.add

<ufunc 'add'>

In [26]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>)>

In [27]:
np.arcsin

<ufunc 'arcsin'>

In [28]:
np.argsort

<function numpy.argsort(a, axis=-1, kind=None, order=None)>

In [29]:
np.amax

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [30]:
np.array_equal

<function numpy.array_equal(a1, a2)>

In [31]:
np.choose

<function numpy.choose(a, choices, out=None, mode='raise')>

In [32]:
np.clip

<function numpy.clip(a, a_min, a_max, out=None, **kwargs)>

In [33]:
np.column_stack

<function numpy.column_stack(tup)>

In [34]:
np.row_stack

<function numpy.vstack(tup)>

In [66]:
np.vstack

<function numpy.vstack(tup)>

In [67]:
np.hstack

<function numpy.hstack(tup)>

In [37]:
np.r_[1,2]

array([1, 2])

In [38]:
np.c_[1,2]

array([[1, 2]])

In [39]:
np.concatenate

<function numpy.concatenate>

In [40]:
np.convolve

<function numpy.convolve(a, v, mode='full')>

In [41]:
np.corrcoef

<function numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>)>

In [42]:
np.cumsum

<function numpy.cumsum(a, axis=None, dtype=None, out=None)>

In [43]:
np.cumprod

<function numpy.cumprod(a, axis=None, dtype=None, out=None)>

In [44]:
np.diag

<function numpy.diag(v, k=0)>

In [55]:
np.diff

<function numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)>

In [45]:
np.dot

<function numpy.dot>

In [46]:
np.dtype

numpy.dtype

In [47]:
np.empty

<function numpy.empty>

In [48]:
np.empty

<function numpy.empty>

In [49]:
np.zeros

<function numpy.zeros>

In [50]:
np.zeros_like

<function numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)>

In [51]:
np.ones

<function numpy.ones(shape, dtype=None, order='C')>

In [52]:
np.ones_like

<function numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)>

In [61]:
np.full

<function numpy.full(shape, fill_value, dtype=None, order='C')>

In [62]:
np.full_like

<function numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)>

In [54]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')>

In [56]:
np.fft

<module 'numpy.fft' from '/home/candar/.local/lib/python3.6/site-packages/numpy/fft/__init__.py'>

In [58]:
np.flip

<function numpy.flip(m, axis=None)>

In [63]:
np.heaviside

<ufunc 'heaviside'>

In [64]:
np.histogram

<function numpy.histogram(a, bins=10, range=None, normed=None, weights=None, density=None)>

In [69]:
np.identity

<function numpy.identity(n, dtype=None)>

In [71]:
np.insert

<function numpy.insert(arr, obj, values, axis=None)>

In [72]:
np.isfinite

<ufunc 'isfinite'>

In [73]:
np.isinf

<ufunc 'isinf'>

In [74]:
np.linalg.det

<function numpy.linalg.det(a)>

In [75]:
np.linalg.eig

<function numpy.linalg.eig(a)>

In [76]:
np.linalg.inv

<function numpy.linalg.inv(a)>

In [77]:
np.linalg.matrix_rank

<function numpy.linalg.matrix_rank(M, tol=None, hermitian=False)>

In [78]:
np.linspace

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [79]:
np.logspace

<function numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)>

In [80]:
np.log

<ufunc 'log'>

In [82]:
np.minimum

<ufunc 'minimum'>

In [83]:
np.maximum

<ufunc 'maximum'>

In [84]:
np.min

<function numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [85]:
np.max

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [86]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>

In [87]:
np.median

<function numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)>

In [88]:
np.matmul

<ufunc 'matmul'>

In [89]:
np.mod

<ufunc 'remainder'>

In [90]:
np.nanmean

<function numpy.nanmean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>

In [92]:
np.outer

<function numpy.outer(a, b, out=None)>

In [93]:
np.percentile

<function numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)>

In [94]:
np.poly

<function numpy.poly(seq_of_zeros)>

In [95]:
np.polyfit

<function numpy.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)>

In [96]:
np.product

<function numpy.product(*args, **kwargs)>

In [97]:
np.ptp

<function numpy.ptp(a, axis=None, out=None, keepdims=<no value>)>

In [99]:
np.random.randn

<function RandomState.randn>

In [100]:
np.random.normal

<function RandomState.normal>

In [101]:
np.random.exponential

<function RandomState.exponential>

In [102]:
np.random.uniform

<function RandomState.uniform>

In [103]:
np.ravel

<function numpy.ravel(a, order='C')>

In [104]:
np.roll

<function numpy.roll(a, shift, axis=None)>

In [105]:
np.reshape

<function numpy.reshape(a, newshape, order='C')>

In [106]:
np.round

<function numpy.round_(a, decimals=0, out=None)>

In [107]:
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

In [108]:
np.str

str

In [109]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [110]:
np.std

<function numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)>

In [112]:
np.take

<function numpy.take(a, indices, axis=None, out=None, mode='raise')>

In [113]:
np.trace

<function numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)>

In [115]:
np.ufunc

numpy.ufunc

In [116]:
np.var

<function numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)>

In [117]:
np.vectorize

numpy.vectorize

In [118]:
np.where

<function numpy.where>