# Chapter 4

@Mert

## Learning Goals

- `numpy` arrays
- `numpy` basics
- vectoral computation


## Authors

- Mert Candar, mccandar@gmail.com
- Aras Kahraman, aras.kahraman@hotmail.com

## Learning Curve Boosters

https://github.com/kyclark/tiny_python_projects

https://github.com/Python-World/python-mini-projects/tree/master/projects

https://github.com/rlvaugh/Impractical_Python_Projects

## An Introduction to `numpy`

The module `numpy` is a handy and comprehensive numerical computation library. @Mert

## Section 1: Arrays

@Mert

In [2]:
import numpy as np

In [69]:
d = [4,5,6,7]
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [70]:
type(arr)

numpy.ndarray

In [68]:
# dir(arr)

In [71]:
d = (4,5,6,7)
arr = np.array(d)
arr

array([4, 5, 6, 7])

In [72]:
d = range(5)
arr = np.array(d)
arr

array([0, 1, 2, 3, 4])

In [73]:
arr.shape

(5,)

In [74]:
arr.ndim

1

In [75]:
d = [
    [1 , 6,  3,    5  ],
    [-1, 4, -3,    17 ],
    [38, 1, -0.45, 0.0],
]
arr = np.array(d)
arr

array([[ 1.  ,  6.  ,  3.  ,  5.  ],
       [-1.  ,  4.  , -3.  , 17.  ],
       [38.  ,  1.  , -0.45,  0.  ]])

In [76]:
arr.shape

(3, 4)

In [77]:
arr.ndim

2

In [78]:
arr[0]

array([1., 6., 3., 5.])

In [79]:
arr[1:]

array([[-1.  ,  4.  , -3.  , 17.  ],
       [38.  ,  1.  , -0.45,  0.  ]])

In [80]:
arr[2,2]

-0.45

In [81]:
arr[1:,2]

array([-3.  , -0.45])

In [82]:
arr[1:,1:]

array([[ 4.  , -3.  , 17.  ],
       [ 1.  , -0.45,  0.  ]])

In [83]:
arr[-1:,2]

array([-0.45])

In [86]:
arr.reshape(2,6)

array([[ 1.  ,  6.  ,  3.  ,  5.  , -1.  ,  4.  ],
       [-3.  , 17.  , 38.  ,  1.  , -0.45,  0.  ]])

In [87]:
arr.reshape(2,6)

array([[ 1.  ,  6.  ,  3.  ,  5.  , -1.  ,  4.  ],
       [-3.  , 17.  , 38.  ,  1.  , -0.45,  0.  ]])

In [88]:
arr.reshape(4,3)

array([[ 1.  ,  6.  ,  3.  ],
       [ 5.  , -1.  ,  4.  ],
       [-3.  , 17.  , 38.  ],
       [ 1.  , -0.45,  0.  ]])

In [89]:
arr.reshape(-1,12)

array([[ 1.  ,  6.  ,  3.  ,  5.  , -1.  ,  4.  , -3.  , 17.  , 38.  ,
         1.  , -0.45,  0.  ]])

In [90]:
arr.reshape(12,)

array([ 1.  ,  6.  ,  3.  ,  5.  , -1.  ,  4.  , -3.  , 17.  , 38.  ,
        1.  , -0.45,  0.  ])

In [91]:
arr.reshape(12,-1)

array([[ 1.  ],
       [ 6.  ],
       [ 3.  ],
       [ 5.  ],
       [-1.  ],
       [ 4.  ],
       [-3.  ],
       [17.  ],
       [38.  ],
       [ 1.  ],
       [-0.45],
       [ 0.  ]])

In [92]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 12 into shape (4,5)

### 1.1(????) Dimensionality

In [106]:
new_array = np.random.randint(1,100,size=20)
new_array

array([18, 71, 46, 24, 60, 85, 34, 37, 25, 80, 32, 18, 30,  4, 25,  6, 20,
       22, 21, 68])

In [107]:
new_array.max()

85

In [108]:
new_array.min()

4

In [109]:
new_array.sum()

726

In [110]:
new_array.mean()

36.3

In [111]:
new_array.std()

23.401068351680014

In [112]:
new_array.var()

547.61

In [113]:
new_array.argmin()

13

In [114]:
new_array.argmax()

5

In [115]:
idx = new_array.argsort()
idx

array([13, 15,  0, 11, 16, 18, 17,  3,  8, 14, 12, 10,  6,  7,  2,  4, 19,
        1,  9,  5])

In [116]:
new_array

array([18, 71, 46, 24, 60, 85, 34, 37, 25, 80, 32, 18, 30,  4, 25,  6, 20,
       22, 21, 68])

In [117]:
new_array[idx]

array([ 4,  6, 18, 18, 20, 21, 22, 24, 25, 25, 30, 32, 34, 37, 46, 60, 68,
       71, 80, 85])

In [118]:
new_array = np.random.randint(1,100,size=(20,5))
new_array

array([[37, 63, 47, 81, 75],
       [88, 36, 89, 73, 22],
       [19, 54, 40, 80, 93],
       [62, 11, 43, 81, 94],
       [ 6, 40,  5, 50, 16],
       [86, 53, 18, 43, 12],
       [91, 95, 55, 42, 50],
       [29, 50, 27, 47, 62],
       [60, 39, 34, 73, 18],
       [49, 94, 23, 22, 86],
       [ 2, 86,  4, 27, 79],
       [47,  8, 10, 34, 82],
       [28, 48, 74, 89, 89],
       [75, 55, 30, 55, 66],
       [44, 74, 94, 50, 18],
       [20, 51, 65, 48, 33],
       [24,  4, 29, 39, 30],
       [74, 43, 96, 68, 85],
       [33, 62,  4, 80, 45],
       [12, 12, 71, 69, 91]])

In [119]:
new_array.max()

96

In [120]:
new_array.min()

2

In [121]:
new_array.sum()

5019

In [122]:
new_array.mean()

50.19

In [123]:
new_array.std()

27.318380259451693

In [124]:
new_array.var()

746.2938999999999

In [125]:
new_array.argmin()

50

In [126]:
new_array.argmax()

87

In [127]:
idx = new_array.argsort()
idx

array([[0, 2, 1, 4, 3],
       [4, 1, 3, 0, 2],
       [0, 2, 1, 3, 4],
       [1, 2, 0, 3, 4],
       [2, 0, 4, 1, 3],
       [4, 2, 3, 1, 0],
       [3, 4, 2, 0, 1],
       [2, 0, 3, 1, 4],
       [4, 2, 1, 0, 3],
       [3, 2, 0, 4, 1],
       [0, 2, 3, 4, 1],
       [1, 2, 3, 0, 4],
       [0, 1, 2, 3, 4],
       [2, 1, 3, 4, 0],
       [4, 0, 3, 1, 2],
       [0, 4, 3, 1, 2],
       [1, 0, 2, 4, 3],
       [1, 3, 0, 4, 2],
       [2, 0, 4, 1, 3],
       [0, 1, 3, 2, 4]])

In [128]:
new_array

array([[37, 63, 47, 81, 75],
       [88, 36, 89, 73, 22],
       [19, 54, 40, 80, 93],
       [62, 11, 43, 81, 94],
       [ 6, 40,  5, 50, 16],
       [86, 53, 18, 43, 12],
       [91, 95, 55, 42, 50],
       [29, 50, 27, 47, 62],
       [60, 39, 34, 73, 18],
       [49, 94, 23, 22, 86],
       [ 2, 86,  4, 27, 79],
       [47,  8, 10, 34, 82],
       [28, 48, 74, 89, 89],
       [75, 55, 30, 55, 66],
       [44, 74, 94, 50, 18],
       [20, 51, 65, 48, 33],
       [24,  4, 29, 39, 30],
       [74, 43, 96, 68, 85],
       [33, 62,  4, 80, 45],
       [12, 12, 71, 69, 91]])

In [129]:
new_array[idx]

array([[[37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93],
        [88, 36, 89, 73, 22],
        [ 6, 40,  5, 50, 16],
        [62, 11, 43, 81, 94]],

       [[ 6, 40,  5, 50, 16],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94],
        [37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93]],

       [[37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16]],

       [[88, 36, 89, 73, 22],
        [19, 54, 40, 80, 93],
        [37, 63, 47, 81, 75],
        [62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16]],

       [[19, 54, 40, 80, 93],
        [37, 63, 47, 81, 75],
        [ 6, 40,  5, 50, 16],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94]],

       [[ 6, 40,  5, 50, 16],
        [19, 54, 40, 80, 93],
        [62, 11, 43, 81, 94],
        [88, 36, 89, 73, 22],
        [37, 63, 47, 81, 75]],

       [[62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16],
        [19, 54, 40, 80, 93]

In [130]:
print(new_array.max())
print(new_array.max(axis=0))
print(new_array.max(axis=1))

96
[91 95 96 89 94]
[81 89 93 94 50 86 95 62 73 94 86 82 89 75 94 65 39 96 80 91]


In [131]:
print(new_array.min())
print(new_array.min(axis=0))
print(new_array.min(axis=1))

2
[ 2  4  4 22 12]
[37 22 19 11  5 12 42 27 18 22  2  8 28 30 18 20  4 43  4 12]


In [132]:
print(new_array.sum())
print(new_array.sum(axis=0))
print(new_array.sum(axis=1))

5019
[ 886  978  858 1151 1146]


In [133]:
print(new_array.mean())
print(new_array.mean(axis=0))
print(new_array.mean(axis=1))

50.19
[44.3  48.9  42.9  57.55 57.3 ]
[60.6 61.6 57.2 58.2 23.4 42.4 66.6 43.  44.8 54.8 39.6 36.2 65.6 56.2
 56.  43.4 25.2 73.2 44.8 51. ]


In [123]:
new_array.std()

27.318380259451693

In [124]:
new_array.var()

746.2938999999999

In [134]:
new_array.argmin()

array([10, 16, 10,  9,  5])

In [126]:
new_array.argmax()

87

In [127]:
idx = new_array.argsort()
idx

array([[0, 2, 1, 4, 3],
       [4, 1, 3, 0, 2],
       [0, 2, 1, 3, 4],
       [1, 2, 0, 3, 4],
       [2, 0, 4, 1, 3],
       [4, 2, 3, 1, 0],
       [3, 4, 2, 0, 1],
       [2, 0, 3, 1, 4],
       [4, 2, 1, 0, 3],
       [3, 2, 0, 4, 1],
       [0, 2, 3, 4, 1],
       [1, 2, 3, 0, 4],
       [0, 1, 2, 3, 4],
       [2, 1, 3, 4, 0],
       [4, 0, 3, 1, 2],
       [0, 4, 3, 1, 2],
       [1, 0, 2, 4, 3],
       [1, 3, 0, 4, 2],
       [2, 0, 4, 1, 3],
       [0, 1, 3, 2, 4]])

In [128]:
new_array

array([[37, 63, 47, 81, 75],
       [88, 36, 89, 73, 22],
       [19, 54, 40, 80, 93],
       [62, 11, 43, 81, 94],
       [ 6, 40,  5, 50, 16],
       [86, 53, 18, 43, 12],
       [91, 95, 55, 42, 50],
       [29, 50, 27, 47, 62],
       [60, 39, 34, 73, 18],
       [49, 94, 23, 22, 86],
       [ 2, 86,  4, 27, 79],
       [47,  8, 10, 34, 82],
       [28, 48, 74, 89, 89],
       [75, 55, 30, 55, 66],
       [44, 74, 94, 50, 18],
       [20, 51, 65, 48, 33],
       [24,  4, 29, 39, 30],
       [74, 43, 96, 68, 85],
       [33, 62,  4, 80, 45],
       [12, 12, 71, 69, 91]])

In [129]:
new_array[idx]

array([[[37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93],
        [88, 36, 89, 73, 22],
        [ 6, 40,  5, 50, 16],
        [62, 11, 43, 81, 94]],

       [[ 6, 40,  5, 50, 16],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94],
        [37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93]],

       [[37, 63, 47, 81, 75],
        [19, 54, 40, 80, 93],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16]],

       [[88, 36, 89, 73, 22],
        [19, 54, 40, 80, 93],
        [37, 63, 47, 81, 75],
        [62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16]],

       [[19, 54, 40, 80, 93],
        [37, 63, 47, 81, 75],
        [ 6, 40,  5, 50, 16],
        [88, 36, 89, 73, 22],
        [62, 11, 43, 81, 94]],

       [[ 6, 40,  5, 50, 16],
        [19, 54, 40, 80, 93],
        [62, 11, 43, 81, 94],
        [88, 36, 89, 73, 22],
        [37, 63, 47, 81, 75]],

       [[62, 11, 43, 81, 94],
        [ 6, 40,  5, 50, 16],
        [19, 54, 40, 80, 93]

In [141]:
# 3 dimensional tensor
new_array = np.random.randint(1,100,size=(3,6,4))
new_array

array([[[68, 46, 99,  3],
        [70, 97, 22, 59],
        [71, 77, 89, 66],
        [65, 54, 95, 35],
        [64, 99, 64, 73],
        [44, 35, 98, 41]],

       [[79,  2, 28, 42],
        [67, 89, 85, 79],
        [44, 39, 13, 99],
        [22,  8, 20,  5],
        [69, 33, 25, 56],
        [90, 75, 78, 55]],

       [[ 5, 95, 72, 68],
        [27, 82, 98,  5],
        [43, 98, 96,  4],
        [71, 77, 31, 10],
        [24, 15, 42, 42],
        [41, 22, 68, 53]]])

In [145]:
print(new_array.mean())
print(new_array.mean(axis=0))
print(new_array.mean(axis=1))
print(new_array.mean(axis=2))

54.513888888888886
[[50.66666667 47.66666667 66.33333333 37.66666667]
 [54.66666667 89.33333333 68.33333333 47.66666667]
 [52.66666667 71.33333333 66.         56.33333333]
 [52.66666667 46.33333333 48.66666667 16.66666667]
 [52.33333333 49.         43.66666667 57.        ]
 [58.33333333 44.         81.33333333 49.66666667]]
[[63.66666667 68.         77.83333333 46.16666667]
 [61.83333333 41.         41.5        56.        ]
 [35.16666667 64.83333333 67.83333333 30.33333333]]
[[54.   62.   75.75 62.25 75.   54.5 ]
 [37.75 80.   48.75 13.75 45.75 74.5 ]
 [60.   53.   60.25 47.25 30.75 46.  ]]


## Section 2: Functions

In [ ]:
np.abs

In [34]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### 2.1 Vectorized Computation (Find the correct location)

........ @Mert

In [35]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [36]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [37]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [38]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [39]:
np.random.randint(0,10)

9

In [40]:
np.random.randint(1,10,5)

array([4, 7, 6, 8, 5])

In [41]:
np.random.rand(5)

array([0.63344674, 0.77764655, 0.94850245, 0.75443283, 0.3101319 ])

In [42]:
np.random.randn(10)

array([-0.55513361,  0.18437941,  0.79585015, -0.19234661,  0.24580945,
        0.23411159, -2.12719165, -0.27157672, -0.05958649,  0.90615033])

In [95]:
arry = np.arange(25)

In [96]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr2 = [4,-5,6,-7]
np.absolute(arr2)

array([4, 5, 6, 7])

In [152]:
np.add?

In [16]:
arr

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [17]:
a = [
    [8,14,6,2],
    [4,5,6,7],
    [4,8,7,2],
    [1,5,2,4],
]
arr3 = np.array(a)
arr3

array([[ 8, 14,  6,  2],
       [ 4,  5,  6,  7],
       [ 4,  8,  7,  2],
       [ 1,  5,  2,  4]])

In [18]:
np.add(arr,arr3)

array([[12, 19, 12,  9],
       [ 8, 10, 12, 14],
       [ 8, 13, 13,  9],
       [ 5, 10,  8, 11]])

In [151]:
np.any?

In [21]:
np.any([-1, 0, 5])

True

In [19]:
np.any([[True, False], [True, True]])

True

In [20]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

In [150]:
np.arcsin?

In [22]:
arr4 = np.array([1,-1,0.1])
np.arcsin(arr4)

array([ 1.57079633, -1.57079633,  0.10016742])

In [28]:
np.argsort

<function numpy.argsort(a, axis=-1, kind=None, order=None)>

In [23]:
arr5 = np.array([2, 0, 1, 5, 4, 1, 9])
np.argsort(arr5)

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [25]:
arr5[np.argsort(arr5)]

array([0, 1, 1, 2, 4, 5, 9])

In [29]:
np.amax

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [26]:
np.amax(arr5)

9

In [30]:
np.array_equal

<function numpy.array_equal(a1, a2)>

In [27]:
arr6 = np.arange(4)
arr7 = [7, 4, 6, 7]
np.array_equal(arr6, arr7)

False

In [28]:
arr6 = np.arange(4)
arr7 = np.arange(4)
np.array_equal(arr6, arr7)

True

In [32]:
np.clip

<function numpy.clip(a, a_min, a_max, out=None, **kwargs)>

In [29]:
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8 ])
np.clip(arr8,2,6)

array([2, 2, 3, 4, 5, 6, 6, 6])

In [33]:
np.column_stack

<function numpy.column_stack(tup)>

In [30]:
arr8 = np.array([ 1, 2, 3 ])
arr9 = np.array([ 4, 5, 6 ])
np.column_stack([arr8, arr9])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.row_stack

<function numpy.vstack(tup)>

In [31]:
arr10 = np.array([1, 2, 3, 4])
np.row_stack(arr10)

array([[1],
       [2],
       [3],
       [4]])

In [66]:
np.vstack

<function numpy.vstack(tup)>

In [36]:
print(arr8)
print(arr9)
np.vstack([arr8, arr9])

[1 2 3]
[4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.hstack

<function numpy.hstack(tup)>

In [37]:
np.hstack([arr8, arr9])

array([1, 2, 3, 4, 5, 6])

In [37]:
np.r_[1,2]

array([1, 2])

In [38]:
np.c_[1,2]

array([[1, 2]])

In [39]:
np.concatenate

<function numpy.concatenate>

In [38]:
np.concatenate((arr8,arr9))

array([1, 2, 3, 4, 5, 6])

In [40]:
np.convolve

<function numpy.convolve(a, v, mode='full')>

In [39]:
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [162]:
np.diff([5,6,4,1])

array([ 1, -2, -3])

In [163]:
np.diff([5,6,4,1],n=2)

array([-3, -1])

In [186]:
d = np.random.randn(100000)
d

array([ 0.30580761, -0.13344078, -1.01594971, ..., -1.01366302,
       -0.0216464 , -0.72898087])

In [174]:
res = np.histogram(d)
freq, bins = res

In [180]:
freq

array([  2,   9,  43, 126, 245, 259, 216,  79,  18,   3])

In [181]:
bins

array([-3.75248304, -3.04359777, -2.33471251, -1.62582724, -0.91694197,
       -0.2080567 ,  0.50082857,  1.20971384,  1.91859911,  2.62748437,
        3.33636964])

In [191]:
np.corrcoef?

In [193]:
np.corrcoef(
    [1,2,3,4],
    [2,4,6,8]
)[0][1]

1.0

In [194]:
np.corrcoef(
    [1,2,3,4],
    [2,4,6,-5]
)[0][1]

-0.512391895472064

In [195]:
np.corrcoef(
    [1,2,3,4],
    [-2,-4,-6,-8]
)[0][1]

-1.0

In [42]:
np.cumsum

<function numpy.cumsum(a, axis=None, dtype=None, out=None)>

In [42]:
arr11 = np.array([[1,2,3], [4,5,6]])

In [45]:
arr11.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [48]:
arr11.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [49]:
arr11.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [43]:
np.cumprod

<function numpy.cumprod(a, axis=None, dtype=None, out=None)>

In [130]:
np.cumprod(arr11)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [44]:
np.diag

<function numpy.diag(v, k=0)>

In [133]:
arr12 = np.array([[1, 21, 30], 
                 [63 ,434, 3], 
                 [54, 54, 56]])
arr12

array([[  1,  21,  30],
       [ 63, 434,   3],
       [ 54,  54,  56]])

In [137]:
np.diag(arr12)

array([  1, 434,  56])

In [139]:
np.diag(arr12, 1)

array([21,  3])

In [140]:
np.diag(arr12, -1)

array([63, 54])

In [55]:
np.diff

<function numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)>

In [141]:
arr13 = np.array([10, 15, 25, 5])

In [144]:
np.diff(arr13)

array([  5,  10, -20])

In [145]:
np.diff(arr13, n=2)

array([  5, -30])

In [146]:
arr14 = np.array([[1, 2, 3, 5], [4, 6, 7, 9]])

In [148]:
np.diff(arr14, axis = 0)

array([[3, 4, 4, 4]])

In [149]:
np.diff(arr14, axis = 1)

array([[1, 1, 2],
       [2, 1, 2]])

In [45]:
np.dot

<function numpy.dot>

In [154]:
arr15 = np.array([[1,2],[3,4]]) 
arr16 = np.array([[5,6],[7,8]]) 
np.dot(arr15, arr16)

array([[19, 22],
       [43, 50]])

In [46]:
np.dtype #-----------------------< check this

numpy.dtype

In [155]:
arr15.dtype

dtype('int32')

In [156]:
arr17 = np.array(['apple', 'banana', 'cherry'])
arr17.dtype

dtype('<U6')

In [48]:
np.empty #----------------------------------ask

<function numpy.empty>

In [49]:
np.zeros

<function numpy.zeros>

In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.zeros_like

<function numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)>

In [159]:
arr18 = np.arange(10).reshape(5, 2)

In [160]:
np.zeros_like(arr18, float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [165]:
np.zeros_like(arr18, order ='C')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [51]:
np.ones

<function numpy.ones(shape, dtype=None, order='C')>

In [71]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.ones_like

<function numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)>

In [169]:
arr19 = np.arange(20).reshape(5, 4)

In [170]:
arr19

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [171]:
np.ones_like(arr19, float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [172]:
np.ones_like(arr19, order ='C')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
np.full

<function numpy.full(shape, fill_value, dtype=None, order='C')>

In [7]:
np.full([2, 2], 67, dtype = int)

array([[67, 67],
       [67, 67]])

In [6]:
np.full([3, 3], 10.1)

array([[10.1, 10.1, 10.1],
       [10.1, 10.1, 10.1],
       [10.1, 10.1, 10.1]])

In [62]:
np.full_like

<function numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)>

In [11]:
arr20 = np.arange(10).reshape(2, 5)
np.full_like(arr20, 10.0)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [12]:
arr21 = np.arange(10, dtype = float).reshape(2, 5)
np.full_like(arr21, 0.01)

array([[0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01]])

In [54]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')>

In [166]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
np.fft #--------------------------------------< ask

<module 'numpy.fft' from '/home/candar/.local/lib/python3.6/site-packages/numpy/fft/__init__.py'>

In [58]:
np.flip

<function numpy.flip(m, axis=None)>

In [15]:
arr22 = np.arange(8).reshape((2,2,2))
arr22

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
np.flip(arr22, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [63]:
np.heaviside

<ufunc 'heaviside'>

In [17]:
arr23 = np.array([-1.5, 0.5, 0, 0.5, 1.5])

hvsd = np.heaviside(x, 0.5)
  
print(hvsd)

[[0.5 1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]]


In [64]:
np.histogram #------------------------------------------------<ask

<function numpy.histogram(a, bins=10, range=None, normed=None, weights=None, density=None)>

In [21]:
arr24 = np.random.randint(100, size=50)
arr24

array([73, 13, 97, 33, 80, 11, 29, 15,  4, 49, 62, 48, 92, 48, 89,  8, 26,
       52, 43, 14, 12, 68, 44, 52, 35, 82, 24, 98, 18, 68, 50, 86, 25, 51,
       64, 73, 11, 91, 33,  6, 13, 82, 94, 60, 31, 93, 44, 19, 67, 39])

In [23]:
np.histogram(arr24, bins = [0, 10, 20, 30, 40,
                        50, 60, 70, 80, 90,
                        100])
  
hist, bins = np.histogram(arr24, bins = [0, 10, 
                                     20, 30,
                                     40, 50,
                                     60, 70,
                                     80, 90,
                                     100])
print()
print (hist) 
print (bins) 
print()


[3 9 4 5 6 4 6 2 5 6]
[  0  10  20  30  40  50  60  70  80  90 100]



In [69]:
np.identity

<function numpy.identity(n, dtype=None)>

In [26]:
arr25 = np.identity(2, dtype = float)
arr25

array([[1., 0.],
       [0., 1.]])

In [71]:
np.insert

<function numpy.insert(arr, obj, values, axis=None)>

In [27]:
arr26 = np.arange(5)
arr26

array([0, 1, 2, 3, 4])

In [29]:
arr26_ins = np.insert(arr26, 1, 9)
arr26_ins

array([0, 9, 1, 2, 3, 4])

In [30]:
arr27 = np.arange(12).reshape(3, 4)
arr27

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr27_ins = np.insert(arr27, 1, 9, axis = 1)
arr27_ins

array([[ 0,  9,  1,  2,  3],
       [ 4,  9,  5,  6,  7],
       [ 8,  9,  9, 10, 11]])

In [72]:
np.isfinite

<ufunc 'isfinite'>

In [37]:
print(np.isfinite(1))
  
print(np.isfinite(0))
  
print(np.isfinite(np.nan))
  
print(np.isfinite(np.inf))
  
print(np.isfinite(np.NINF))

True
True
False
False
False


In [33]:
arr28 = np.arange(20).reshape(5, 4)
arr28                 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
np.isfinite(arr28)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
np.isinf

<ufunc 'isinf'>

In [38]:
print(np.isinf(1))
  
print(np.isinf(0))
  
print(np.isinf(np.nan))
  
print(np.isinf(np.inf))
  
print(np.isinf(np.NINF))

False
False
False
True
True


In [39]:
np.isinf(arr28)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [74]:
np.linalg.det

<function numpy.linalg.det(a)>

In [41]:
arr29 = np.array([[1, 2], [3, 4]])

In [42]:
np.linalg.det(arr29)

-2.0000000000000004

In [3]:
np.linalg.eig #----------------------------------<ask

<function numpy.linalg.eig(a)>

In [76]:
np.linalg.inv

<function numpy.linalg.inv(a)>

In [7]:
arr30 = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

np.linalg.inv(arr30)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [8]:
arr31 = np.array([[[1., 2.], [3., 4.]],
              [[1, 3], [3, 5]]])
  
np.linalg.inv(arr31)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

In [77]:
np.linalg.matrix_rank #--------------------------------------<ask

<function numpy.linalg.matrix_rank(M, tol=None, hermitian=False)>

In [79]:
np.logspace

<function numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)>

In [13]:
np.logspace(2.0, 3.0, num=5, base = 11)

array([ 121.        ,  220.36039471,  401.31159963,  730.8527479 ,
       1331.        ])

In [14]:
np.logspace(2.0, 3.0, num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [15]:
np.logspace(2.0, 3.0, num=5, dtype = int)

array([ 100,  177,  316,  562, 1000])

In [80]:
np.log

<ufunc 'log'>

In [8]:
b = [1, 3, 5, 2**8]
  
np.log(b)

array([0.        , 1.09861229, 1.60943791, 5.54517744])

In [9]:
np.log([1, np.e, np.e**2, 0])

<ipython-input-9-12cefd5fc7db>:1: RuntimeWarning: divide by zero encountered in log
  np.log([1, np.e, np.e**2, 0])


array([  0.,   1.,   2., -inf])

In [13]:
np.minimum

In [10]:
arr32 = [2, 8, 125]
arr33 = [3, 3, 15]
    
np.minimum(arr32, arr33) 

array([ 2,  3, 15])

In [83]:
np.maximum 

<ufunc 'maximum'>

In [11]:
arr32 = [2, 8, 125]
arr33 = [3, 3, 15]
    
np.maximum(arr32, arr33) 

array([  3,   8, 125])

In [12]:
np.min #--------------------------------------<ask

In [85]:
np.max #----------------------------------------<ask

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [86]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>

In [15]:
arr34 = [20, 2, 7, 1, 34]
  
np.mean(arr34)

12.8

In [18]:
arr35 = [[14, 17, 12, 33, 44],  
         [15, 6, 27, 8, 19], 
         [23, 2, 54, 1, 4, ]] 
    
print(np.mean(arr35))
    
print(np.mean(arr35, axis = 0))
   
print(np.mean(arr35, axis = 1))

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


In [87]:
np.median

<function numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)>

In [22]:
arr36 = [20, 2, 7, 1, 34]
  
np.median(arr36)

7.0

In [23]:
arr37 = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4, ]] 
     
print(np.median(arr37)) 
     
print(np.median(arr37, axis = 0)) 
   
print(np.median(arr37, axis = 1))

15.0
[15.  6. 27.  8. 19.]
[17. 15.  4.]


In [88]:
np.matmul

<ufunc 'matmul'>

In [24]:
arr38 = np.array([[1, 2, 3], [4, 5, 6],
                 [7, 8, 9]])

arr39 = np.array([[11, 12, 13], [14, 15, 16],
                 [17, 18, 19]])
  
np.matmul(arr38, arr39)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [89]:
np.mod

<ufunc 'remainder'>

In [25]:
num1 = 6
num2 = 4
    
np.mod(num1, num2)

2

In [26]:
arr40 = np.array([2, -4, 7])
arr41 = np.array([2, 3, 4])
    
np.mod(arr40, arr41)

array([0, 2, 3], dtype=int32)

In [90]:
np.nanmean

<function numpy.nanmean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>

In [27]:
arr42 = np.array([[20, 15, 37], [47, 13, np.nan]]) 
    
print(np.mean(arr42))
    
print(np.nanmean(arr42)) 

nan
26.4


In [28]:
arr43 = np.array([[32, 20, 24], 
                  [47, 63, np.nan],   
                  [17, 28, np.nan],
                  [10, 8, 9]]) 
    
    
print(np.mean(arr43, axis = 0)) 
    
print(np.nanmean(arr43, axis = 0)) 

[26.5  29.75   nan]
[26.5  29.75 16.5 ]


In [92]:
np.outer

<function numpy.outer(a, b, out=None)>

In [29]:
a = np.ones(4)
b = np.linspace(-1, 2, 4)

In [32]:
np.outer(a, b)

array([[-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.]])

In [93]:
np.percentile

<function numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)>

In [33]:
arr44 = [20, 2, 7, 1, 34]

print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

15.0
7.0
25.0


In [35]:
arr45 = [[14, 17, 12, 33, 44], 
         [15, 6, 27, 8, 19],
         [23, 2, 54, 1, 4,]]

print(np.percentile(arr, 50))

print(np.percentile(arr, 0))
    
print(np.percentile(arr, 50, axis =0))

print(np.percentile(arr, 0, axis =0))

15.0
1.0
[15.  6. 27.  8. 19.]
[14.  2. 12.  1.  4.]


In [94]:
np.poly #-------------------------------<ask

<function numpy.poly(seq_of_zeros)>

In [95]:
np.polyfit #-----------------------------<ask

<function numpy.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)>

In [96]:
np.product

<function numpy.product(*args, **kwargs)>

In [38]:
arr46 = [4, 2]
 
np.prod(arr46)

8

In [40]:
arr47 = [[1., 2.], [3., 4.]]

np.prod(arr47)

24.0

In [41]:
arr48 =[[1, 2], [3, 4]]

np.prod(arr48, axis = 1)

array([ 2, 12])

In [46]:
arr45 = [[14, 17, 12, 33, 44], 
         [15, 6, 27, 8, 19],
         [23, 2, 54, 1, 4,]]
np.prod(arr45, axis = 1)

array([4146912,  369360,    9936])

In [97]:
np.ptp

<function numpy.ptp(a, axis=None, out=None, keepdims=<no value>)>

In [49]:
arr49 = [1, 2, 7, 10, 16]
np.ptp(arr49)

15

In [50]:
arr50 = [1, 2, 7, 20, np.nan]
np.ptp(arr50)

nan

In [51]:
arr51 = [[14, 17, 12, 33, 44],  
         [15, 6, 27, 8, 19], 
         [23, 2, 54, 1, 4,]] 

print(np.ptp(arr51)) 

print(np.ptp(arr51, axis = 0)) 

print(np.ptp(arr51, axis = 1))

53
[ 9 15 42 32 40]
[32 21 53]


In [100]:
np.random.normal

<function RandomState.normal>

In [101]:
np.random.exponential

<function RandomState.exponential>

In [102]:
np.random.uniform

<function RandomState.uniform>

In [103]:
np.ravel #------------------------------------<ask

<function numpy.ravel(a, order='C')>

In [56]:
arr52 = np.arange(15).reshape(3, 5)

print(np.ravel(arr52))
print(np.ravel(arr52, order = 'K'))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [104]:
np.roll

<function numpy.roll(a, shift, axis=None)>

In [59]:
arr53 = np.arange(12).reshape(3, 4)

print(arr53)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
print(np.roll(arr53, 1))

[[11  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


In [61]:
print(np.roll(arr53, 5))

[[ 7  8  9 10]
 [11  0  1  2]
 [ 3  4  5  6]]


In [62]:
print(np.roll(arr53, 2, axis = 0))

[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [106]:
np.round

<function numpy.round_(a, decimals=0, out=None)>

In [65]:
arr54 = [0.5, 1.5, 2.55, 3.44, 4.8, 10.1]
  
np.round(arr54)

array([ 0.,  2.,  3.,  3.,  5., 10.])

In [68]:
arr55 = [.5538, 1.33354, .71445]

np.round(arr55, decimals = 3)

array([0.554, 1.334, 0.714])

In [69]:
arr56 = [147, 301, 466, 449, 12]
  
np.round(arr56, decimals = -2)

array([100, 300, 500, 400,   0])

In [70]:
arr56 = [147, 301, 466, 449, 12]
  
np.round(arr56, decimals = -3)

array([0, 0, 0, 0, 0])

In [107]:
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

In [73]:
a = np.array([[12, 15], [10, 1]])

a_sort = np.sort(a, axis = 0)  

print(a_sort)        

[[10  1]
 [12 15]]


In [74]:
b = np.array([[8, 7], [44, 9]])

b_sort = np.sort(b, axis = -1)

print(b_sort)

[[ 7  8]
 [ 9 44]]


In [76]:
c = np.array([[3, 15], [7, 11]])

c_sort = np.sort(c, axis = None)    

print(c_sort)

[ 3  7 11 15]


In [108]:
np.str #---------------------------------<ask

str

In [109]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [3]:
arr57 = [20, 2, 0.2, 10, 4]  
   
print(np.sum(arr57)) 
   
print(np.sum(arr57, dtype = np.uint8))

print(np.sum(arr57, dtype = np.float32))

36.2
36
36.2


In [6]:
arr58 = [[14, 17, 12, 33, 44],   
         [15, 6, 27, 8, 19],  
         [23, 2, 54, 1, 4,]]  
   
print(np.sum(arr58)) 
   
print(np.sum(arr58, dtype = np.uint8))

print(np.sum(arr58, dtype = np.float32))

print(np.sum(arr58, axis = 0)) 

print(np.sum(arr58, axis = 1))

279
23
279.0
[52 25 93 42 67]
[120  75  84]


In [110]:
np.std

<function numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)>

In [7]:
arr59 = [20, 2, 7, 1, 34]
   
print(np.std(arr59))

print(np.std(arr59, dtype = np.float32))
  
print(np.std(arr59, dtype = np.float64))

12.576167937809991
12.576168
12.576167937809991


In [9]:
arr60 = [[2, 2, 2, 2, 2],  
         [15, 6, 27, 8, 2], 
         [23, 2, 54, 1, 2, ], 
         [11, 44, 34, 7, 2]] 

print(np.std(arr60)) 

print( np.std(arr60, axis = 0)) 

print(np.std(arr60, axis = 1))

15.3668474320532
[ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]
[ 0.          8.7772433  20.53874388 16.40243884]


In [112]:
np.take

<function numpy.take(a, indices, axis=None, out=None, mode='raise')>

In [12]:
arr61 = [[5, 6, 2, 7, 1],
         [4, 9, 2, 9, 3]]


print(np.take(arr61, [0, 4]))

[5 1]


In [13]:
print(np.take(arr61, [0, 4], axis = 1))

[[5 1]
 [4 3]]


In [113]:
np.trace #----------------------------------<ask

<function numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)>

In [16]:
arr61 = [[5, 6, 2, 7, 1],
         [4, 9, 2, 9, 3]]

np.trace(arr61)

14

In [35]:
arr62 = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 8]')
np.trace(arr62)

15

In [19]:
np.ufunc #---------------------------------<ask

In [116]:
np.var

<function numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)>

In [36]:
arr63 = [20, 8 , 7, 1, 71] 
 
print(np.var(arr63)) 
  
print(np.var(arr63, dtype = np.float32)) 

print(np.var(arr63, dtype = np.float64)) 

653.0400000000001
653.04004
653.0400000000001


In [37]:
arr64 = [[2, 2, 2, 2, 2], 
         [15, 6, 27, 8, 2], 
         [23, 2, 54, 1, 2,], 
         [11, 44, 34, 7, 2]] 
  

print(np.var(arr64)) 

print(np.var(arr64, axis = 0)) 

print(np.var(arr64, axis = 1))

236.14000000000004
[ 57.1875 312.75   345.6875   9.25     0.    ]
[  0.    77.04 421.84 269.04]


In [117]:
np.vectorize #---------------------------------<ask

numpy.vectorize

In [118]:
np.where

<function numpy.where>

In [38]:
arr65 = np.arange(5,10)

print(arr65)

np.where(arr65 < 8)

[5 6 7 8 9]


(array([0, 1, 2], dtype=int64),)

In [39]:
arr65[np.where(arr65 < 8)] 

array([5, 6, 7])

In [40]:
arr66 = np.arange(4,10).reshape(2,3)
arr66

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
np.where(arr66 > 8)

(array([1], dtype=int64), array([2], dtype=int64))

In [45]:
arr66[np.where(arr66 > 8)]

array([9])